#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ofertas.Resource", IsApplication=true)]

namespace Ofertas
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040013
			public const int btbGoogle = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int btnFace = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int btnLogin = 2130968594;
			
			// aapt resource value: 0x7f04000c
			public const int btnNovo = 2130968588;
			
			// aapt resource value: 0x7f04001c
			public const int btnPublic = 2130968604;
			
			// aapt resource value: 0x7f040023
			public const int btnSalvar = 2130968611;
			
			// aapt resource value: 0x7f04001f
			public const int editText1 = 2130968607;
			
			// aapt resource value: 0x7f04001d
			public const int imageButton1 = 2130968605;
			
			// aapt resource value: 0x7f040001
			public const int imageView1 = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int imageView2 = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int imageView3 = 2130968584;
			
			// aapt resource value: 0x7f040019
			public const int img1 = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int img2 = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int img3 = 2130968603;
			
			// aapt resource value: 0x7f040000
			public const int linearLayout1 = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int linearLayout2 = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int linearLayout3 = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int linearLayout4 = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int linearLayout5 = 2130968585;
			
			// aapt resource value: 0x7f040022
			public const int rbFem = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int rbMasc = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int scrollView1 = 2130968608;
			
			// aapt resource value: 0x7f04000d
			public const int space1 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int space2 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int space3 = 2130968591;
			
			// aapt resource value: 0x7f040018
			public const int spinCateg = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int spinSuper = 2130968599;
			
			// aapt resource value: 0x7f040005
			public const int textView1 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int textView2 = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int textView3 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int textView4 = 2130968587;
			
			// aapt resource value: 0x7f040016
			public const int txtDescricao = 2130968598;
			
			// aapt resource value: 0x7f040010
			public const int txtEmail = 2130968592;
			
			// aapt resource value: 0x7f04001e
			public const int txtNome = 2130968606;
			
			// aapt resource value: 0x7f040011
			public const int txtSenha = 2130968593;
			
			// aapt resource value: 0x7f040015
			public const int txtTitulo = 2130968597;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Feed = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int NovoPost = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Perfil = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
